from Sem07Atv01Q01 import *
peixe1 = peixe(40, 'Pirarucú', 'Água doce')
peixe2 = peixe(4, 'Tambaquí', 'Água doce')
peixe3 = peixe(900, 'Tubarão','Água salgada')
cachorro1 = cachorro(2, 'Mel', 'Pincher')
cachorro2 = cachorro(16, 'Frederico', 'Golden')
cachorro3 = cachorro(30, 'Thor', 'Pitbull')
print('#=' * 30)
print('PEIXES:')
print(peixe1)
print('==' * 30)
print(peixe2)
print('==' * 30)
print(peixe3)
print('#=' * 30)
print('CACHORROS:')
print(cachorro1)
print('==' * 30)
print(cachorro2)
print('==' * 30)
print(cachorro3)
print('#=' * 30)